#!/usr/bin/env python
# -*- coding: utf8 -*-

###############
#   CONFIG    #
###############
plugins = {
    'all' : [
        'plugin_0_init',
        'plugin_1_config',
        'plugin_2_auth',
        'plugin_3_mail',
        'plugin_4_common',
        'plugin_5_lang_helper',
        'plugin_6_mail_helper',
        'plugin_7_auth_action_helpers',
        'plugin_8_recaptcha_wrapper',
        'plugin_9_auth_helpers',
        'plugin_blog',
        'plugin_ckeditor',
        'plugin_cliniqueafricaine',
        'plugin_contact',
        'plugin_dashboard',
        'plugin_emelitautomat',
        'plugin_external',
        'plugin_inception',
        'plugin_kamite',
        'plugin_menu',
        'plugin_mtnmomo',
        'plugin_mychallenge',
        'plugin_mystream',
        'plugin_projectmia',
        'plugin_pusher',
        'plugin_sqldesigner',
        'plugin_tests',
        'plugin_theme_cosmo',
        'plugin_theme_default',
        'plugin_theme_emelit',
        'plugin_theme_projectmia',
        'plugin_threejs',
        'plugin_utils',
        'plugin_w2p_ajax_upload',
        'plugin_wiki',
        'plugin_zz_final',
    ],

    'mystream' : [
        'plugin_0_init',
        'plugin_1_config',
        'plugin_2_auth',
        'plugin_3_mail',
        'plugin_4_common',
        'plugin_5_lang_helper',
        'plugin_6_mail_helper',
        'plugin_7_auth_action_helpers',
        'plugin_8_recaptcha_wrapper',
        'plugin_9_auth_helpers',
        'plugin_blog',
        'plugin_ckeditor',
        'plugin_contact',
        'plugin_menu',
        'plugin_mystream',
        'plugin_theme_cosmo',
    ],

    'projectmia' : [
        'plugin_0_init',
        'plugin_1_config',
        'plugin_2_auth',
        'plugin_3_mail',
        'plugin_4_common',
        'plugin_5_lang_helper',
        'plugin_6_mail_helper',
        'plugin_7_auth_action_helpers',
        'plugin_8_recaptcha_wrapper',
        'plugin_9_auth_helpers',
        'plugin_blog',
        'plugin_ckeditor',
        'plugin_contact',
        'plugin_menu',
        'plugin_mystream',
        'plugin_projectmia',
        'plugin_theme_cosmo',
        'plugin_theme_projectmia',
        'plugin_utils',
    ],

    'conf-comm-ck-mystream-mia' : [
        'plugin_1_config',
        'plugin_4_common',
        'plugin_ckeditor',
        'plugin_mystream',
        'plugin_projectmia',
        'plugin_theme_cosmo',
        'plugin_theme_projectmia',
    ],
}
macro_path_config = {
    'script_path': './',
    'path': 'macros',
    'base':     'macro-kantu.base.json',
    'commands': {
        'download': 'macro-kantu.commands.json',
        'upload': 'macro-kantu.upload-commands.json',
    },
    'end_commands': 'macro-kantu.end.json',
    'output':   'macro-kantu-%s.json',
    'download':   '/home/nkensa/Downloads/Downloads/web2py.%s.w2p',
    'upload':   '/home/nkensa/GDrive/Tree/Workspaces/dev/frameworks/web2py/plugins/molhokwai/web2py.%s.w2p',
    'git_script_path': '/mnt/FA80688B80684FE5/GDrive/Tree/Workspaces/2/emelit/src/copy-and-commit',
}
