#!/usr/bin/env python
print "##################################################################"
print "#    web2py plugins download macro and processing                #"
print "#    --------------------------------------------                #"
print "#    Script to generate kantu macro addon|plugin json for        #"
print "#    automatic web2py plugins download and processing            #"
print "#    (commit, push)                                              #"
print "#                                                                #"
print "#    Usage:                                                      #"
print "#    ------                                                      #"
print "#    -   ./process [action]  [app_name] [web2py app/site url]    #"
print "#                                                                #"
print "#    Calls:                                                      #"
print "#    ------                                                      #"
print "#        ./process macro projectmia                              #"
print "#                  https://.../.../admin/design/emelit#plugins   #"
print "#        ./process macro projectmia                              #"
print "#                  https://.../.../admin/design/emelit#plugins   #"
print "#                  upload                                        #"
print "#                  https://.../.../admin/design/emelit           #"
print "#            generates plugins download | upload macros json     #"
print "#            (kantu macro addon|plugin)                          #"
print "#        ./process file projectmia                               #"
print "#            generates plugins local placeholder files           #"
print "#            (kantu macro addon|plugin)                          #"
print "#        ./process download                                      #"
print "#            process downloaded plugins:                         #"
print "#            - move to plugin folder                             #"
print "#            - uploads (to gdrive, could be github...)           #"
print "#                                                                #"
print "#        complete command samples:                                #"
print "#            - download macro json generation: ./process macro projectmia https://molhokwwai.pythonanywhere.com/admin/design/emelit#plugins       #"
print "#            - upload macro json generation: ./process macro projectmia http://127.0.0.1:8000/admin/design/emelit#plugins upload http://127.0.0.1:8000/admin/design/emelit                        #"
print "#                                                                #"
print "#                                                                #"
print "##################################################################"



import sys, os, re, json, datetime

###############
#   HELPERS   #
###############
class MacroPathHelper():
    _dict = {}
    def __init__(self, config, action):
        for name in config:
            self._dict[name] = config[name]
        self.action = action

    def __getattr__(self, name):
        import os
        if name in ('output'):
            path = os.path.join(self.path, self.action)
            if not os.path.exists(path):
                os.makedirs(path)
            return os.path.join(self.path, self.action, self._dict[name])

        if name in ('script_path', 'git_script_path', 'after_upload_url'):
            return self._dict[name]

        elif name not in ('path'):
            return os.path.join(self.path, self._dict[name])

        else:
            return os.path.join(self._dict['path'])

    def get_command_path(self, which='download'):
        return os.path.join(self.path, self._dict['commands'][which])

    def get_transfer_path(self, plugin_name, which='download'):
        return str(self._dict[which] % plugin_name)\
              .replace('web2py.plugin_', 'web2py.plugin.')


###############
#   CONFIG    #
###############
plugins = {
    'all' : [
        'plugin_0_init',
        'plugin_1_config',
        'plugin_2_auth',
        'plugin_3_mail',
        'plugin_4_common',
        'plugin_5_lang_helper',
        'plugin_6_mail_helper',
        'plugin_7_auth_action_helpers',
        'plugin_8_recaptcha_wrapper',
        'plugin_9_auth_helpers',
        'plugin_blog',
        'plugin_ckeditor',
        'plugin_cliniqueafricaine',
        'plugin_contact',
        'plugin_dashboard',
        'plugin_emelitautomat',
        'plugin_external',
        'plugin_inception',
        'plugin_kamite',
        'plugin_menu',
        'plugin_mtnmomo',
        'plugin_mychallenge',
        'plugin_mystream',
        'plugin_projectmia',
        'plugin_pusher',
        'plugin_sqldesigner',
        'plugin_tests',
        'plugin_theme_cosmo',
        'plugin_theme_default',
        'plugin_theme_emelit',
        'plugin_theme_projectmia',
        'plugin_threejs',
        'plugin_utils',
        'plugin_w2p_ajax_upload',
        'plugin_wiki',
        'plugin_zz_final',
    ],

    'mystream' : [
        'plugin_0_init',
        'plugin_1_config',
        'plugin_2_auth',
        'plugin_3_mail',
        'plugin_4_common',
        'plugin_5_lang_helper',
        'plugin_6_mail_helper',
        'plugin_7_auth_action_helpers',
        'plugin_8_recaptcha_wrapper',
        'plugin_9_auth_helpers',
        'plugin_blog',
        'plugin_ckeditor',
        'plugin_contact',
        'plugin_menu',
        'plugin_mystream',
        'plugin_theme_cosmo',
    ],

    'projectmia' : [
        'plugin_0_init',
        'plugin_1_config',
        'plugin_2_auth',
        'plugin_3_mail',
        'plugin_4_common',
        'plugin_5_lang_helper',
        'plugin_6_mail_helper',
        'plugin_7_auth_action_helpers',
        'plugin_8_recaptcha_wrapper',
        'plugin_9_auth_helpers',
        'plugin_blog',
        'plugin_ckeditor',
        'plugin_contact',
        'plugin_menu',
        'plugin_mystream',
        'plugin_projectmia',
        'plugin_theme_cosmo',
        'plugin_theme_projectmia',
        'plugin_utils',
    ],
}
macro_path_config = {
    'script_path': './',
    'path': 'macros',
    'base':     'macro-kantu.base.json',
    'commands': {
        'download': 'macro-kantu.commands.json',
        'upload': 'macro-kantu.upload-commands.json',
    },
    'end_commands': 'macro-kantu.end.json',
    'output':   'macro-kantu-%s.json',
    'download':   '/home/nkensa/Downloads/Downloads/web2py.%s.w2p',
    'upload':   '/home/nkensa/GDrive/Tree/Workspaces/dev/frameworks/web2py/plugins/molhokwai/web2py.%s.w2p',
    'git_script_path': '/mnt/FA80688B80684FE5/GDrive/Tree/Workspaces/2/emelit/src/copy-and-commit',
}


###############
#   PROCESS   #
###############
## arguments
a = ''
name = ''
url = 'https://molhokwai.pythonanywhere.com/admin/design/emelit#plugins'
args = []

i = 0
for arg in sys.argv:    
    if i == 1: a = arg
    elif i == 2: name = arg
    elif i == 3: url = arg
    elif i > 3: args.append(arg)

    i += 1


## process
print
print
print 'Begin...'
print

l = plugins.get(name, plugins['all'])
if len(re.findall(r'plugin|file', a)):
    print 'Writing files...'
    for item in l:
        if not os.path.exists(name):
            os.makedirs(name)
        open(os.path.join(name, '%s.py' % item), 'w').write('')


if len(re.findall(r'json|macro', a)):
    print 'Writing macro json...'
    
    _a = args[0] if len(args)>0 else 'download'
    macro_path = MacroPathHelper(macro_path_config, name)
    commands = open(macro_path.get_command_path(which=_a)).read()
    output = json.loads(open(macro_path.base).read() % dict(
        date_time=datetime.datetime.now().strftime('%Y-%m-%d'), url=url))
    
    for item in l:
        if _a in ('download'):
            output['Commands'] += json.loads(commands % dict(plugin_name=item))['Commands']
        else:
            # -Setting upload source not supported:
            #   upload_src = macro_path.get_transfer_path(item, which='upload')
            after_upload_url = args[1] if len(args)>1 else url
            output['Commands'] += json.loads(commands % 
                    dict(plugin_name=item,
                         after_upload_url=after_upload_url)
            )['Commands']
    output['Commands'] += json.loads(open(macro_path.end_commands).read())['Commands']
    
    open(os.path.join(macro_path.output % _a), 'w').write(json.dumps(output, indent=4))


if len(re.findall(r'download', a)):
    print 'Processing downloads...'
    
    macro_path = MacroPathHelper(macro_path_config, '')
    
    _fs = filter(lambda x: os.path.exists(x), map(lambda x: macro_path.get_transfer_path(x), l))
    if _fs:
        _fs = ' '.join(_fs)
        os.system('mv %(files)s %(dest)s' % dict(files=_fs, dest=macro_path.script_path))
        os.system('drive push')

        print 'Enter git commit message:'
        os.system('%s %s' % (macro_path.git_script_path, '"%s"' % raw_input()))
    else:
        print 'No downloads'


print
print 'Done.'
print
print
